[project]
name = "mswpr-python-dependencies"
version = "0.1.0"
description = "mswpr Python dependencies"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "conan>=2.24.0",
]
